fixed indentation

diff --git a/nama b/nama
--- a/nama
+++ b/nama
@@ -57,7 +57,7 @@ done
 
 ## Checks if the script runs as root
 Root_Check () {
-	if [[ $Runasroot_ARG -eq 1 ]]; then
+	if [[ $Runasroot_ARG -ne 0 ]]; then
 		return 0
 	elif  [[ $EUID -eq 0 ]]; then
 		printf "$line\n"
@@ -70,10 +70,10 @@ Root_Check () {
 ## Declare function’s variables, create and validate log files
 Log_And_Variables () {
 
-	####  Varibale	####
+	####  Variable	####
 	line=$(printf '%40s\n' | tr ' ' -)
-  	logpath=/tmp/NAM.log
-	####  Varibale	####
+  logpath=/tmp/NAM.log
+	####  Variable	####
 
 
 
@@ -120,47 +120,47 @@ Filter_Active_Interfaces () {
 ## and notify the user, if no interfaces exist exit the program
 Active_Interfaces_Menu (){
     if [[ ${#Filtered_Active_Interfaces[@]} -eq 0 ]]; then
-        echo No interface is found, exiting.
-            sleep 1
-            exit 0
+      echo No interface is found, exiting.
+      sleep 1
+      exit 0
     elif [[ ${#Filtered_Active_Interfaces[@]} -eq 1 ]]; then
-        echo Only ${Filtered_Active_Interfaces[0]} is connected, and will be used
-        option=${Filtered_Active_Interfaces[0]}
-        sleep 1
+      echo Only ${Filtered_Active_Interfaces[0]} is connected, and will be used
+      option=${Filtered_Active_Interfaces[0]}
+      sleep 1
 		elif [[ Scripted -eq 1 ]]; then
-		 		echo  "More then one interface was found,
-				this is not supported in non-interactive mode,
-				please use -i to select an interface"
+		 	echo  "More then one interface was found,
+			this is not supported in non-interactive mode,
+			please use -i to select an interface"
     else
-        echo "Please select the interface you wish to use"
-        arrsize=$(expr 1 + $1)
-        select option in "${@:2}"; do
-            if [ "$REPLY" -eq "$arrsize" ]; then
-                echo "Exiting..."
-                break;
-            elif [ 1 -le "$REPLY" ] && [ "$REPLY" -le $((arrsize-1)) ]; then
-                echo "You selected $option which is option $REPLY"
-                sleep 1
-                echo ""
-                break;
-            else
-                echo "Incorrect Input: Select a number 1-$arrsize"
-            fi
-        done
+      echo "Please select the interface you wish to use"
+      arrsize=$(expr 1 + $1)
+      select option in "${@:2}"; do
+        if [ "$REPLY" -eq "$arrsize" ]; then
+          echo "Exiting..."
+          break;
+        elif [ 1 -le "$REPLY" ] && [ "$REPLY" -le $((arrsize-1)) ]; then
+          echo "You selected $option which is option $REPLY"
+          sleep 1
+          echo ""
+          break;
+      	else
+          echo "Incorrect Input: Select a number 1-$arrsize"
+        fi
+			done
     fi
 }
 
 ## Gather information about the interface, ip address,
 ## netmask(bit length format), gateway and name servers
 Interface_Info () {
-    echo "Gathering information..."
-    echo ""
-    sleep 1
-    # Extract ip, netmask and gateway
-    declare Ip_Info=$(ip addr show $option | awk '{if(NR==3) print $2}')
-    Ip=$(ip addr show $option | awk '{if(NR==3) print $2}' |cut -d "/" -f "1")
-    Netmask=$(echo $Ip_Info | cut -d "/" -f "2")
-    Gateway=$(ip route show  | awk 'NR==1 {print $3}')
+  echo "Gathering information..."
+  echo ""
+  sleep 1
+  # Extract ip, netmask and gateway
+  declare Ip_Info=$(ip addr show $option | awk '{if(NR==3) print $2}')
+  Ip=$(ip addr show $option | awk '{if(NR==3) print $2}' |cut -d "/" -f "1")
+  Netmask=$(echo $Ip_Info | cut -d "/" -f "2")
+  Gateway=$(ip route show  | awk 'NR==1 {print $3}')
 }
 
 
@@ -256,15 +256,13 @@ Verify_Info () {
   echo " "
   read -p "Is the information correct? [Y,n]" currect
   until [[ $currect == "" ]] || [[ $currect == "y" ]] ||\
-  [[ $currect == "Y" ]] || [[ $currect == "n" ]] || \
-  [[ $currect == "N" ]]; do
-	echo "Invalid input, try again"
-	read -p "Is the information correct? [Y,n]" currect
+  			[[ $currect == "Y" ]] || [[ $currect == "n" ]] || \
+  			[[ $currect == "N" ]]; do
+		echo "Invalid input, try again"
+		read -p "Is the information correct? [Y,n]" currect
   done
-
   if [[ $currect == "" ]] || [[ $currect == "y" ]] || [[ $currect == "Y" ]]; then
     :
-
   elif [[ $currect == "n" ]] || [[ $currect == "N" ]]; then
     echo " "
     echo $line
@@ -327,8 +325,8 @@ Clone_Profile () {
 ## This function deactivates the active profile and activates the new profile,
 ## then informs the user
 Activate_New_Profile () {
-   nmcli con down "$Active_Profile" && nmcli con up "$New_Profile" -a
-   echo "Profile $New_Profile activated"
+ nmcli con down "$Active_Profile" && nmcli con up "$New_Profile" -a
+ echo "Profile $New_Profile activated"
  }
 
 
@@ -396,14 +394,14 @@ Help_Function () {
 
 ## This script runs all the functions
 Main () {
-	if [[ $Version_ARG -eq 1 ]]; then
+	if [[ $Version_ARG -ne 0 ]]; then
 		echo "NAM version $NAM_Version"
 	fi
 	## Verify that no argument is being used, and use the standard version
 	if [[ "$Ipv4_ARG" == 0 ]] && [[ $Gateway_ARG == 0 ]] && \
-	[[ $Netmask_ARG == 0 ]] && [[ $DNS1_ARG == 0 ]] && \
-	[[ $DNS2_ARG == 0 ]] && [[ $Profile_ARG == 0 ]] && \
-	[[ $Force_ARG -eq 0 ]] && [[ $Help_ARG -eq 0 ]] ; then
+	   [[ $Netmask_ARG == 0 ]] && [[ $DNS1_ARG == 0 ]] && \
+	   [[ $DNS2_ARG == 0 ]] && [[ $Profile_ARG == 0 ]] && \
+     [[ $Force_ARG -eq 0 ]] && [[ $Help_ARG -eq 0 ]] ; then
 		echo $line
 		Root_Check
 		Log_And_Variables
@@ -419,69 +417,69 @@ Main () {
 	## Check if all the flags needed to be configured are used, and no interfearing
 	## flags have been used
 	elif [[ $Ipv4_ARG != 0 ]] && [[ $Gateway_ARG != 0 ]] && \
-		[[ $Netmask_ARG != 0 ]] && [[ $DNS1_ARG != 0 ]] && \
-		[[ $DNS2_ARG != 0 ]] && [[ $Profile_ARG != 0 ]] && \
-		[[ $Help_ARG -eq 0 ]] ; then
-			Scripted=1
-			if ! Ipv4_Verify $Ipv4_ARG ;then
-				echo "IP address is invalid, exiting" |tee $logpath
-				exit 1
-			elif ! Ipv4_Verify $Gateway_ARG ;then
-				echo "gateway is invalid, exiting" |tee $logpath
-				exit 1
-			elif ! Ipv4_Verify $DNS1_ARG ;then
-				echo "DNS1 is invalid, exiting" |tee $logpath
-				exit 1
-			elif ! Ipv4_Verify $DNS2_ARG ;then
-				echo "DNS2 is invalid, exiting" |tee $logpath
-				exit 1
-			elif [[ ! "$Netmask_ARG" -gt 1  ||  ! "$Netmask_ARG" -lt 32 ]] ;then
-				echo "Netmask is invalid, exiting" |tee $logpath
-				exit
-			fi
-			Root_Check
-			Log_And_Variables
-			KDE_Check
-			if [[ $Interface_ARG == 0 ]]; then
-				Filter_Active_Interfaces
-				Active_Interfaces_Menu "${#Filtered_Active_Interfaces[@]}" "${Filtered_Active_Interfaces[@]}"
-			elif ! [[ -z $(nmcli --t -f NAME,UUID,TYPE,DEVICE con show --active |  grep $Interface_ARG |cut -d ":" -f 1) ]] ; then
-				option=$Interface_ARG
-			else
-				echo "$Interface_ARG in not an active interface, exiting"
-				exit 1
-			fi
-			New_Ip=$Ipv4_ARG
-			New_Netmask=$Netmask_ARG
-			New_Gateway=$Gateway_ARG
-			New_DNS1=$DNS1_ARG
-			New_DNS2=$DNS2_ARG
-			nmcli con show "$Profile_ARG"  &> $logpath
-		  if [[ $? -eq 0 ]] && [[ $Force_ARG -eq 0 ]];then
-				echo "Profile name is already in use,"
-				echo "you can use -f to force overwrite"
-		    exit 1
-			elif nmcli con show "$Profile_ARG"  &> $logpath && [[ $Force_ARG -ne 0 ]]; then
-				New_Profile=$Profile_ARG
-				Active_Profile=$( nmcli --t -f NAME,UUID,TYPE,DEVICE con show --active |  grep $option |cut -d ":" -f 1 )
-				nmcli con mod "$New_Profile" ipv4.method manual ipv4.addr "$New_Ip/$New_Netmask" ipv4.gateway "$New_Gateway" ipv4.dns "$New_DNS1 $New_DNS2" &> $logpath
-		  else
-		    New_Profile=$Profile_ARG
-				Clone_Profile
-		  fi
-			Activate_New_Profile
-			exit 0
-		## check if only the Help flag is on
-	elif [[ $Ipv4_ARG == 0 ]] && [[ $Gateway_ARG == 0 ]] && \
-		[[ $Netmask_ARG == 0 ]] && [[ $DNS1_ARG == 0 ]] && \
-		[[ $DNS2_ARG == 0 ]] && [[ $Profile_ARG == 0 ]] && \
-		[[ $Force_ARG -eq 0 ]] && [[ $Help_ARG -ne 0 ]] ; then
-			Help_Function
-			exit 0
+	     [[ $Netmask_ARG != 0 ]] && [[ $DNS1_ARG != 0 ]] && \
+	     [[ $DNS2_ARG != 0 ]] && [[ $Profile_ARG != 0 ]] && \
+		   [[ $Help_ARG -eq 0 ]] ; then
+		Scripted=1
+		if ! Ipv4_Verify $Ipv4_ARG ;then
+			echo "IP address is invalid, exiting" |tee $logpath
+			exit 1
+		elif ! Ipv4_Verify $Gateway_ARG ;then
+			echo "gateway is invalid, exiting" |tee $logpath
+			exit 1
+		elif ! Ipv4_Verify $DNS1_ARG ;then
+			echo "DNS1 is invalid, exiting" |tee $logpath
+			exit 1
+		elif ! Ipv4_Verify $DNS2_ARG ;then
+			echo "DNS2 is invalid, exiting" |tee $logpath
+			exit 1
+		elif [[ ! "$Netmask_ARG" -gt 1  ||  ! "$Netmask_ARG" -lt 32 ]] ;then
+			echo "Netmask is invalid, exiting" |tee $logpath
+			exit
+		fi
+		Root_Check
+		Log_And_Variables
+		KDE_Check
+		if [[ $Interface_ARG == 0 ]]; then
+			Filter_Active_Interfaces
+			Active_Interfaces_Menu "${#Filtered_Active_Interfaces[@]}" "${Filtered_Active_Interfaces[@]}"
+		elif ! [[ -z $(nmcli --t -f NAME,UUID,TYPE,DEVICE con show --active |  grep $Interface_ARG |cut -d ":" -f 1) ]] ; then
+			option=$Interface_ARG
 		else
-			echo "Missing arguments, use -h for help"
+			echo "$Interface_ARG in not an active interface, exiting"
 			exit 1
 		fi
+		New_Ip=$Ipv4_ARG
+		New_Netmask=$Netmask_ARG
+		New_Gateway=$Gateway_ARG
+		New_DNS1=$DNS1_ARG
+		New_DNS2=$DNS2_ARG
+		nmcli con show "$Profile_ARG"  &> $logpath
+	  if [[ $? -eq 0 ]] && [[ $Force_ARG -eq 0 ]];then
+			echo "Profile name is already in use,"
+			echo "you can use -f to force overwrite"
+	    exit 1
+		elif nmcli con show "$Profile_ARG"  &> $logpath && [[ $Force_ARG -ne 0 ]]; then
+			New_Profile=$Profile_ARG
+			Active_Profile=$( nmcli --t -f NAME,UUID,TYPE,DEVICE con show --active |  grep $option |cut -d ":" -f 1 )
+			nmcli con mod "$New_Profile" ipv4.method manual ipv4.addr "$New_Ip/$New_Netmask" ipv4.gateway "$New_Gateway" ipv4.dns "$New_DNS1 $New_DNS2" &> $logpath
+	  else
+	    New_Profile=$Profile_ARG
+			Clone_Profile
+	  fi
+		Activate_New_Profile
+		exit 0
+		## check if only the Help flag is on
+	elif [[ $Ipv4_ARG == 0 ]] && [[ $Gateway_ARG == 0 ]] && \
+		   [[ $Netmask_ARG == 0 ]] && [[ $DNS1_ARG == 0 ]] && \
+		   [[ $DNS2_ARG == 0 ]] && [[ $Profile_ARG == 0 ]] && \
+		   [[ $Force_ARG -eq 0 ]] && [[ $Help_ARG -ne 0 ]] ; then
+		Help_Function
+		exit 0
+	else
+		echo "Missing arguments, use -h for help"
+		exit 1
+	fi
 }
 
 Main
