added --version to nama and to man page

diff --git a/nama b/nama
--- a/nama
+++ b/nama
@@ -39,7 +39,7 @@ while true; do
 	case "$1" in
 		-h|--help) Help_ARG=1; shift ;;
 		-f )	Force_ARG=1; shift ;;
-		-V ) Version_ARG=1; shift ;;
+		-V | --version) Version_ARG=1; shift ;;
 		-i ) Interface_ARG=$2; shift 2;;
 		-p ) Profile_ARG=$2; shift 2 ;;
 		--ipv4 ) Ipv4_ARG=$2; shift 2 ;;
@@ -345,49 +345,53 @@ Ipv4_Verify () {
 
 ## Display help to the user
 Help_Function () {
-printf "%s" "\
-Usage: nama --option \"value\" --option \"value\"
-nama (Network Automated Manager)
-This script will use nmcli to set up static ip efortlessly.
+	printf "%s" "\
+	Usage: nama --option \"value\" --option \"value\"
+	nama (Network Automated Manager)
+	This script will use nmcli to set up static ip efortlessly.
 
-Options:
+	Options:
 
-    -f                          if profile name is used, force overwrite
+	    -f                          if profile name is used, force overwrite
 
-    -i <Active interface>       active interface to be used
+	    -i <Active interface>       active interface to be used
 
-    -p <Profile name>           name of the profile to be created
+	    -p <Profile name>           name of the profile to be created
 
-    --ipv4 <ipv4 address>       valid ipv4 address to be used
+			-V                          Display the current version of nama
 
-    --netmask <netmask>         netmask to be used, in bit-length format
+	    --ipv4 <ipv4 address>       valid ipv4 address to be used
 
-    --gateway <gateway>         gateway address to be used
+	    --netmask <netmask>         netmask to be used, in bit-length format
 
-    --dns1 <dns address>        primary name server address to be used
+	    --gateway <gateway>         gateway address to be used
 
-    --dns2 <dns address>        secondary name server address to be used
+	    --dns1 <dns address>        primary name server address to be used
 
-    --runasroot                 Enable the option to run the script as root
+	    --dns2 <dns address>        secondary name server address to be used
 
+	    --runasroot                 Enable the option to run the script as root
 
-Example:
-
-	sudo nama -i enp0s3 -p test --ipv4 192.168.1.1 --netmask 24 --gateway 192.168.1.10 --dns1 1.1.1.1 --dns2 9.9.9.9 --runasroot
-
-Authors:
-
-	chn555
-		https://github.com/chn555
-
-	BigRush
-		https://github.com/BigRush
+			--version                   Display the current version of nama
 
 
+	Example:
 
-For any bugs please report to https://github.com/chn555/nama/issues
+		sudo nama -i enp0s3 -p test --ipv4 192.168.1.1 --netmask 24 --gateway 192.168.1.10 --dns1 1.1.1.1 --dns2 9.9.9.9 --runasroot
 
-"
+	Authors:
+
+		chn555
+			https://github.com/chn555
+
+		BigRush
+			https://github.com/BigRush
+
+
+
+	For any bugs please report to https://github.com/chn555/nama/issues
+
+	"
 }
 
 ## This script runs all the functions
@@ -414,70 +418,70 @@ Main () {
 		exit 0
 	## Check if all the flags needed to be configured are used, and no interfearing
 	## flags have been used
-elif [[ $Ipv4_ARG != 0 ]] && [[ $Gateway_ARG != 0 ]] && \
-	[[ $Netmask_ARG != 0 ]] && [[ $DNS1_ARG != 0 ]] && \
-	[[ $DNS2_ARG != 0 ]] && [[ $Profile_ARG != 0 ]] && \
-	[[ $Help_ARG -eq 0 ]] ; then
-		Scripted=1
-		if ! Ipv4_Verify $Ipv4_ARG ;then
-			echo "IP address is invalid, exiting" |tee $logpath
-			exit 1
-		elif ! Ipv4_Verify $Gateway_ARG ;then
-			echo "gateway is invalid, exiting" |tee $logpath
-			exit 1
-		elif ! Ipv4_Verify $DNS1_ARG ;then
-			echo "DNS1 is invalid, exiting" |tee $logpath
-			exit 1
-		elif ! Ipv4_Verify $DNS2_ARG ;then
-			echo "DNS2 is invalid, exiting" |tee $logpath
-			exit 1
-		elif [[ ! "$Netmask_ARG" -gt 1  ||  ! "$Netmask_ARG" -lt 32 ]] ;then
-			echo "Netmask is invalid, exiting" |tee $logpath
-			exit
-		fi
-		Root_Check
-		Log_And_Variables
-		KDE_Check
-		if [[ $Interface_ARG == 0 ]]; then
-			Filter_Active_Interfaces
-			Active_Interfaces_Menu "${#Filtered_Active_Interfaces[@]}" "${Filtered_Active_Interfaces[@]}"
-		elif ! [[ -z $(nmcli --t -f NAME,UUID,TYPE,DEVICE con show --active |  grep $Interface_ARG |cut -d ":" -f 1) ]] ; then
-			option=$Interface_ARG
+	elif [[ $Ipv4_ARG != 0 ]] && [[ $Gateway_ARG != 0 ]] && \
+		[[ $Netmask_ARG != 0 ]] && [[ $DNS1_ARG != 0 ]] && \
+		[[ $DNS2_ARG != 0 ]] && [[ $Profile_ARG != 0 ]] && \
+		[[ $Help_ARG -eq 0 ]] ; then
+			Scripted=1
+			if ! Ipv4_Verify $Ipv4_ARG ;then
+				echo "IP address is invalid, exiting" |tee $logpath
+				exit 1
+			elif ! Ipv4_Verify $Gateway_ARG ;then
+				echo "gateway is invalid, exiting" |tee $logpath
+				exit 1
+			elif ! Ipv4_Verify $DNS1_ARG ;then
+				echo "DNS1 is invalid, exiting" |tee $logpath
+				exit 1
+			elif ! Ipv4_Verify $DNS2_ARG ;then
+				echo "DNS2 is invalid, exiting" |tee $logpath
+				exit 1
+			elif [[ ! "$Netmask_ARG" -gt 1  ||  ! "$Netmask_ARG" -lt 32 ]] ;then
+				echo "Netmask is invalid, exiting" |tee $logpath
+				exit
+			fi
+			Root_Check
+			Log_And_Variables
+			KDE_Check
+			if [[ $Interface_ARG == 0 ]]; then
+				Filter_Active_Interfaces
+				Active_Interfaces_Menu "${#Filtered_Active_Interfaces[@]}" "${Filtered_Active_Interfaces[@]}"
+			elif ! [[ -z $(nmcli --t -f NAME,UUID,TYPE,DEVICE con show --active |  grep $Interface_ARG |cut -d ":" -f 1) ]] ; then
+				option=$Interface_ARG
+			else
+				echo "$Interface_ARG in not an active interface, exiting"
+				exit 1
+			fi
+			New_Ip=$Ipv4_ARG
+			New_Netmask=$Netmask_ARG
+			New_Gateway=$Gateway_ARG
+			New_DNS1=$DNS1_ARG
+			New_DNS2=$DNS2_ARG
+			nmcli con show "$Profile_ARG"  &> $logpath
+		  if [[ $? -eq 0 ]] && [[ $Force_ARG -eq 0 ]];then
+				echo "Profile name is already in use,"
+				echo "you can use -f to force overwrite"
+		    exit 1
+			elif nmcli con show "$Profile_ARG"  &> $logpath && [[ $Force_ARG -ne 0 ]]; then
+				New_Profile=$Profile_ARG
+				Active_Profile=$( nmcli --t -f NAME,UUID,TYPE,DEVICE con show --active |  grep $option |cut -d ":" -f 1 )
+				nmcli con mod "$New_Profile" ipv4.method manual ipv4.addr "$New_Ip/$New_Netmask" ipv4.gateway "$New_Gateway" ipv4.dns "$New_DNS1 $New_DNS2" &> $logpath
+		  else
+		    New_Profile=$Profile_ARG
+				Clone_Profile
+		  fi
+			Activate_New_Profile
+			exit 0
+		## check if only the Help flag is on
+	elif [[ $Ipv4_ARG == 0 ]] && [[ $Gateway_ARG == 0 ]] && \
+		[[ $Netmask_ARG == 0 ]] && [[ $DNS1_ARG == 0 ]] && \
+		[[ $DNS2_ARG == 0 ]] && [[ $Profile_ARG == 0 ]] && \
+		[[ $Force_ARG -eq 0 ]] && [[ $Help_ARG -ne 0 ]] ; then
+			Help_Function
+			exit 0
 		else
-			echo "$Interface_ARG in not an active interface, exiting"
+			echo "Missing arguments, use -h for help"
 			exit 1
 		fi
-		New_Ip=$Ipv4_ARG
-		New_Netmask=$Netmask_ARG
-		New_Gateway=$Gateway_ARG
-		New_DNS1=$DNS1_ARG
-		New_DNS2=$DNS2_ARG
-		nmcli con show "$Profile_ARG"  &> $logpath
-	  if [[ $? -eq 0 ]] && [[ $Force_ARG -eq 0 ]];then
-			echo "Profile name is already in use,"
-			echo "you can use -f to force overwrite"
-	    exit 1
-		elif nmcli con show "$Profile_ARG"  &> $logpath && [[ $Force_ARG -ne 0 ]]; then
-			New_Profile=$Profile_ARG
-			Active_Profile=$( nmcli --t -f NAME,UUID,TYPE,DEVICE con show --active |  grep $option |cut -d ":" -f 1 )
-			nmcli con mod "$New_Profile" ipv4.method manual ipv4.addr "$New_Ip/$New_Netmask" ipv4.gateway "$New_Gateway" ipv4.dns "$New_DNS1 $New_DNS2" &> $logpath
-	  else
-	    New_Profile=$Profile_ARG
-			Clone_Profile
-	  fi
-		Activate_New_Profile
-		exit 0
-	## check if only the Help flag is on
-elif [[ $Ipv4_ARG == 0 ]] && [[ $Gateway_ARG == 0 ]] && \
-	[[ $Netmask_ARG == 0 ]] && [[ $DNS1_ARG == 0 ]] && \
-	[[ $DNS2_ARG == 0 ]] && [[ $Profile_ARG == 0 ]] && \
-	[[ $Force_ARG -eq 0 ]] && [[ $Help_ARG -ne 0 ]] ; then
-		Help_Function
-		exit 0
-	else
-		echo "Missing arguments, use -h for help"
-		exit 1
-	fi
 }
 
 Main
